version: 2
jobs:
  Unit Test:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout
      - run:
          command: |
            sudo pip install virtualenv
            sudo pip install nox
            nox -f noxfile.py -s unit
  Lint:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout
      - run:
          command: |
            sudo pip install virtualenv
            sudo pip install nox
            nox -f noxfile.py -s lint

workflows:
  version: 2
  test:
    jobs:
      - Unit Test
      - Lint
